name: phone_connect
description: "Program na propojení PC a telefonu na základě WebRTC"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  network_info_plus: ^6.1.0
  window_manager: ^0.4.2
  path_provider: ^2.1.5
  uuid: ^4.4.2
  hive_ce: ^2.7.0+1
  hive_ce_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_ce_generator: ^1.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/